import { clsx, type ClassValue } from 'clsx'
import { twMerge } from 'tailwind-merge'
export function cn(...inputs: ClassValue[]) { return twMerge(clsx(inputs)) }
export const formatPYG = (n: number) => `₲ ${new Intl.NumberFormat('es-PY').format(Math.round(n))}`
export const formatDate = (d: string | null) => d ? new Date(d).toLocaleDateString('es-PY', { day: '2-digit', month: '2-digit', year: 'numeric' }) : '—'
export const daysUntil = (d: string) => Math.ceil((new Date(d+'T00:00:00').getTime() - new Date().setHours(0,0,0,0)) / 86400000)
export const urgencyBadge = (days: number) => days < 0 ? { label: 'VENCIDO', cls: 'bg-red-100 text-red-800 font-bold' } : days === 0 ? { label: 'HOY', cls: 'bg-red-100 text-red-700 font-bold' } : days <= 3 ? { label: `${days}d`, cls: 'bg-orange-100 text-orange-700' } : days <= 7 ? { label: `${days}d`, cls: 'bg-yellow-100 text-yellow-700' } : { label: `${days}d`, cls: 'bg-green-100 text-green-700' }
export const CASE_STATUS: Record<string, { label: string; cls: string }> = { new: { label: 'Nuevo', cls: 'bg-blue-100 text-blue-800' }, active: { label: 'Activo', cls: 'bg-green-100 text-green-800' }, investigation: { label: 'Investigación', cls: 'bg-purple-100 text-purple-800' }, negotiation: { label: 'Negociación', cls: 'bg-yellow-100 text-yellow-800' }, trial: { label: 'En Juicio', cls: 'bg-orange-100 text-orange-800' }, appeal: { label: 'Apelación', cls: 'bg-indigo-100 text-indigo-800' }, resolution: { label: 'Resolución', cls: 'bg-teal-100 text-teal-800' }, closed_won: { label: 'Ganado', cls: 'bg-emerald-100 text-emerald-800' }, closed_lost: { label: 'Perdido', cls: 'bg-red-100 text-red-800' }, closed_settled: { label: 'Transado', cls: 'bg-gray-100 text-gray-700' }, archived: { label: 'Archivado', cls: 'bg-gray-100 text-gray-500' } }
export const MATTER: Record<string, string> = { civil: 'Civil', penal: 'Penal', laboral: 'Laboral', familia: 'Familia', comercial: 'Comercial', administrativo: 'Administrativo', constitucional: 'Constitucional', tributario: 'Tributario', ambiental: 'Ambiental', inmobiliario: 'Inmobiliario', bancario: 'Bancario', sucesiones: 'Sucesiones', concursal: 'Concursal', internacional: 'Internacional', otro: 'Otro' }
